#!/bin/sh
echo "Mencegah commit jika ada file dengan TODO"
if grep -r "TODO" .; then
    echo "Commit cancelled: cause some code got error
    exit 1
fi

echo "Memeriksa panjang file sebelum commit..."
for file in $(git diff --cached --name-only); do
    if [ -f "$file" ]; then
        char_count=$(wc -c < "$file")
        if [ "$char_count" -lt 10 ]; then
            echo "Commit dibatalkan! File '$file' memiliki kurang dari 10 karakter."
            exit 1
        fi
    fi
done
